apiVersion: apps/v1
kind: Deployment
metadata:
  name: kuber-lesson-2-deploy
  labels:
    app: kuber-lesson-2
    stage: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kuber-lesson-2
  template:
    metadata:
      labels:
        app: kuber-lesson-2
    spec:
      containers:
        - name: levelup
          image: likemaydev/kuber-lesson-2:latest
          ports:
            - containerPort: 80
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: kl2-autoscale
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kuber-lesson-2
  minReplicas: 3
  maxReplicas: 4

  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 50
  - type: Resource
    resource:
      name: memory
      target:
        type: AverageValue
        averageValue: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: kuber-lesson-2-svc
  labels:
    app: kuber-lesson-2
spec:
  type: LoadBalancer
  selector:
    app: kuber-lesson-2
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
